# Archivo: azure-pipelines.yml

trigger:
- main  # O el nombre de la rama que quieres que dispare el pipeline

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.8'  # Ajusta esto a la versión de Python que necesitas

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate
    python -m pip install --upgrade pip
    pip install -r requirements.txt pytest
  displayName: 'Instalar dependencias'

- script: |
    source venv/bin/activate
    python -m pytest
  displayName: 'Ejecutar pruebas'

- script: |
    source venv/bin/activate
    python run.py
  displayName: 'Ejecutar aplicación Flask'
