trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Hola, mundo!"
  displayName: 'Ejecutar un script de una línea'

- script: |
    echo "Agrega otras tareas para construir, probar y desplegar tu proyecto."
    echo "Ver https://aka.ms/yaml"
  displayName: 'Ejecutar un script de varias líneas'

- script: |
    echo "Instalando dependencias..."
    yarn install
  displayName: 'Instalar dependencias'

- script: |
    echo "Construyendo el proyecto..."
    yarn build
  displayName: 'Construir proyecto'

- script: |
    echo "Ejecutando pruebas..."
    yarn test
  displayName: 'Ejecutar pruebas'

- script: |
    echo "Desplegando la aplicación..."
    # Aquí añadirías los comandos para desplegar tu aplicación
  displayName: 'Desplegar aplicación'
